#define HOST_SAMPLE_RATE 48000
#define ZX_VIDEO_HZ 50.08

#define BORDER_WIDTH 16
#define BORDER_HEIGHT 12
#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 192
#define PIXELS_WIDTH (BORDER_WIDTH + SCREEN_WIDTH + BORDER_WIDTH)
#define PIXELS_HEIGHT (BORDER_HEIGHT + SCREEN_HEIGHT + BORDER_HEIGHT)
#define PIXELS_COUNT PIXELS_WIDTH * PIXELS_HEIGHT

#define SCALE_FACTOR 3
#define SURFACE_WIDTH (SCALE_FACTOR * PIXELS_WIDTH)
#define SURFACE_HEIGHT (SCALE_FACTOR * PIXELS_HEIGHT)
