#include <stdint.h>

#define ZXKEY_MOD_CAPS_SHIFT 0x40
#define ZXKEY_MOD_SYM_SHIFT 0x80

#define AUTOTYPE_FRAME_THRESHOLD 84
#define AUTOTYPE_FRAMES_PER_KEY 7

enum {
    ZXKEY_CAPS_SHIFT, ZXKEY_Z,         ZXKEY_X, ZXKEY_C, ZXKEY_V,
    ZXKEY_A,          ZXKEY_S,         ZXKEY_D, ZXKEY_F, ZXKEY_G,
    ZXKEY_Q,          ZXKEY_W,         ZXKEY_E, ZXKEY_R, ZXKEY_T,
    ZXKEY_1,          ZXKEY_2,         ZXKEY_3, ZXKEY_4, ZXKEY_5,
    ZXKEY_0,          ZXKEY_9,         ZXKEY_8, ZXKEY_7, ZXKEY_6,
    ZXKEY_P,          ZXKEY_O,         ZXKEY_I, ZXKEY_U, ZXKEY_Y,
    ZXKEY_ENTER,      ZXKEY_L,         ZXKEY_K, ZXKEY_J, ZXKEY_H,
    ZXKEY_SPACE,      ZXKEY_SYM_SHIFT, ZXKEY_M, ZXKEY_N, ZXKEY_B
};

const uint8_t zxprg_border_test[] = {
    ZXKEY_1, ZXKEY_0, ZXKEY_L, ZXKEY_A, ZXKEY_MOD_SYM_SHIFT | ZXKEY_L, ZXKEY_0, ZXKEY_ENTER,
    ZXKEY_2, ZXKEY_0, ZXKEY_MOD_CAPS_SHIFT | ZXKEY_SYM_SHIFT, ZXKEY_MOD_SYM_SHIFT | ZXKEY_O, ZXKEY_2, ZXKEY_5, ZXKEY_4, ZXKEY_MOD_SYM_SHIFT | ZXKEY_N, ZXKEY_A, ZXKEY_ENTER,
    ZXKEY_3, ZXKEY_0, ZXKEY_L, ZXKEY_A, ZXKEY_MOD_SYM_SHIFT | ZXKEY_L, ZXKEY_A, ZXKEY_MOD_SYM_SHIFT | ZXKEY_K, ZXKEY_1, ZXKEY_MOD_SYM_SHIFT | ZXKEY_Z, ZXKEY_U, ZXKEY_A, ZXKEY_MOD_SYM_SHIFT | ZXKEY_L, ZXKEY_8, ZXKEY_MOD_SYM_SHIFT | ZXKEY_G, ZXKEY_L, ZXKEY_A, ZXKEY_MOD_SYM_SHIFT | ZXKEY_L, ZXKEY_0, ZXKEY_ENTER,
    ZXKEY_4, ZXKEY_0, ZXKEY_G, ZXKEY_2, ZXKEY_0, ZXKEY_ENTER,
    ZXKEY_R, ZXKEY_ENTER,
    0xFF
};
